[package]
name = "esb"
version = "0.0.1"
authors = ["thalesfragoso <thales.fragosoz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic-array = "0.13"
zerocopy = "0.3.0"
heapless = "0.5.4"
nrf51 = { version = "0.9.0", optional = true }
nrf52810-pac = { version = "0.9.0", optional = true }
nrf52832-pac = { version = "0.9.0", optional = true }
nrf52840-pac = { version = "0.9.0", optional = true }
log = { version = "0.4.8", optional = true }

[features]
51 = ["nrf51"]
52810 = ["nrf52810-pac"]
52832 = ["nrf52832-pac"]
52840 = ["nrf52840-pac"]
