on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Continuous integration

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - feature: 51,
            target: thumbv6m-none-eabi
            rust: stable
          - feature: 51,
            target: thumbv6m-none-eabi
            rust: nightly
            experimental: true
          - feature: 52810,
            target: thumbv7em-none-eabi
            rust: stable
          - feature: 52832,
            target: thumbv7em-none-eabihf
            rust: stable
          - feature: 52832,
            target: thumbv7em-none-eabihf
            rust: nightly
            experimental: true
          - feature: 52840,
            target: thumbv7em-none-eabihf
            rust: stable
          - feature: 52832,fast-ru,
            target: thumbv7em-none-eabihf
            rust: stable

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
      - run: rustup target add thumbv7em-none-eabihf thumbv7em-none-eabi thumbv6m-none-eabi

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features=${{ matrix.feature }} --target=${{ matrix.target }}
